# Generated by Django 3.1.7 on 2021-03-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
