# Generated by Django 3.1.7 on 2021-03-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0002_auto_20210318_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
