# Generated by Django 3.1.7 on 2021-03-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0003_auto_20210318_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='offer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.IntegerField(),
        ),
    ]
