# Generated by Django 3.1.7 on 2021-03-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0004_auto_20210319_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='offer',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.FloatField(),
        ),
    ]
