# Generated by Django 3.1.7 on 2021-03-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0006_auto_20210322_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
