# Generated by Django 3.1.7 on 2021-03-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0007_auto_20210322_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='offer',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
