# Generated by Django 3.1.7 on 2021-03-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0009_auto_20210322_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='currency',
        ),
        migrations.AddField(
            model_name='order',
            name='pay_status',
            field=models.CharField(choices=[(1, 'SUCCESS'), (2, 'FAILURE'), (3, 'Complete')], default=3, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'New'), (1, 'Checkout'), (2, 'Paid'), (3, 'Failed'), (4, 'Shipped'), (5, 'Delivered'), (6, 'Returned'), (7, 'Complete')], default=0, max_length=50),
        ),
    ]
