# Generated by Django 3.1.7 on 2021-03-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0010_auto_20210322_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('PENDING', 'PENDING')], default='SUCCESS', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Canceled', 'Canceled'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Returned', 'Returned')], default='Placed', max_length=50),
        ),
    ]
