# Generated by Django 3.1.7 on 2021-04-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0012_auto_20210329_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offer',
            field=models.IntegerField(default=0),
        ),
    ]
