# Generated by Django 3.1.7 on 2021-04-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0014_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(max_length=15),
        ),
    ]
