# Generated by Django 3.1.7 on 2021-03-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='house_name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='contact',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='pin',
            new_name='zip_code',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
