# Generated by Django 3.1.7 on 2021-03-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210320_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image1',
            field=models.ImageField(null=True, upload_to='pp/'),
        ),
    ]
