# Generated by Django 3.1.7 on 2021-03-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_image1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image1',
            new_name='image',
        ),
    ]
